### ISSUE TITLE
elasticsearch_rails: How to disable offset

### ISSUE THREAD

**Issue by Kani999** [ddnexus/pagy#118]
Hello,

I'm defining controller action

```
    query = params[:search_jobs].presence && params[:search_jobs][:query]
    query = '*' if query.blank?

    page = params[:page].to_i
    page = 1 if params[:page].blank?

    elastic_records = AccountingPbsJob.search(query).page(page).records

    @pagy, @accounting_pbs_jobs = pagy_elasticsearch_rails(elastic_records, items: 25)

    render action: "search"
```

When I hit next page the query looks like this:

```
SELECT  `accounting_pbs_jobs`.* 
FROM `accounting_pbs_jobs`
 WHERE `accounting_pbs_jobs`.`id` IN (15430, 15443, 15445, 15454, 15457, 15459, 15463, 15466, 15474, 15475, 15478, 15483, 15484, 15488, 15494, 15512, 15518, 15522, 15523, 15530, 15540, 15544, 15548, 15550, 15560) 
LIMIT 25 
OFFSET 25
```

Query selects 25 records, with offset 25 so the array is empty.

How can I disable offset for selecting records?

```
 @pagy.offset = 0
NoMethodError: undefined method `offset=' for #<Pagy:0x00007f732c42f8a0>
```

**Comment by ddnexus** [comment]
You don't need to restrict to the page: it is done automatically.

```rb
@pagy, @accounting_pbs_jobs = pagy_elasticsearch_rails(AccountingPbsJob.search(query), items: 25)
```

**Comment by Kani999** [comment]
Does not work for me.

```
SELECT COUNT(count_column) FROM 
  (SELECT  1 AS count_column 
   FROM `accounting_pbs_jobs` 
   WHERE `accounting_pbs_jobs`.`id` IN (15430, 15443, 15445, 15454, 15457, 15459, 15463, 15466, 15474, 15475) 
LIMIT 25
 OFFSET 50) subquery_for_count
```

The query returns 0 records because of offset. 

I don't know how to get the next page from Elasticsearch and render it. Could you help me?

```
    query = params[:search_jobs].presence && params[:search_jobs][:query]
    query = '*' if query.blank?

    elastic_records = AccountingPbsJob.search(query).records

    @pagy, @accounting_pbs_jobs = pagy_elasticsearch_rails(elastic_records)

    render action: "search"
```

**Comment by ddnexus** [comment]
It looks like your `params[:search_jobs][:query] ` has already a limitation if specific ids. The collection that you want to paginate includes just the  `(15430, 15443, 15445, 15454, 15457, 15459, 15463, 15466, 15474, 15475)` ids. So THAT is the collection that you are feeding to pagy. I suppose it would work as expected if your query wouldn't limit the ids.

**Comment by Kani999** [comment]
`params[:search_jobs][:query]` contains `*` so called method is  `__elasticsearch__.search('*')`.

The pagy will gets this 10 records.
But with next page, the ids are different (still 10 values) but the offset will change and records = empty array.

- Returns 10 records
```
SELECT COUNT(*) FROM 
   FROM `accounting_pbs_jobs` 
   WHERE `accounting_pbs_jobs`.`id` IN ( (ids from 1 to 10) ) 
LIMIT 10 subquery_for_count
``` 

- Returns 0 records
```
SELECT COUNT(*) FROM 
   FROM `accounting_pbs_jobs` 
   WHERE `accounting_pbs_jobs`.`id` IN ( (ids from 1 to 10) ) 
LIMIT 10 subquery_for_count
Offset 10
```

I don't know what am I doing wrong.

**Comment by workgena** [comment]
By writing this

```SQL
WHERE `accounting_pbs_jobs`.`id` IN ( (ids from 1 to 10) ) 
```

You are saying give me records with ID are: 1,2,3,4,5,6,7,8,9,10

Than you write:

```SQL
LIMIT 10
Offset 10
```

Literally saying give me 10 records (LIMIT), but skip first 10 (OFFSET).
In other words: give me 10 records starting from 11-record to 20-record.

The `WHERE accounting_pbs_jobs.id IN ( (ids from 1 to 10) ) ` restricts returning result to 10 records at all. And all of them are skipped because of `Offset 10`

**Comment by Kani999** [comment]
Exactly. I want to get rid of the offset, but it seems impossible to me. 
I suppose it is some build-in method.

**Comment by workgena** [comment]
@Kani999 I've deleted my message, because I misunderstand the problem, and my answer is unexpected in this case.

**Comment by ddnexus** [comment]
@Kani999 
I don't think the solution would be getting rid of the offset, however since I don't know Elasticsearch Rails at all, so I better involve the author of the extra @renshuki that can certainly help you.

**Comment by ddnexus** [comment]
See #123.

**Comment by ddnexus** [comment]
Fixed with the refactoring in branch [v2.0-dev](https://github.com/ddnexus/pagy/tree/v2.0-dev)

**Comment by renshuki** [comment]
I didn't notice the problem with the offset, thank you for the refactoring @ddnexus.

**Comment by ddnexus** [comment]
The refactoring changed also the way to use it. I added also the support for the `items` extra and the `:page_param`. 

I am refactoring also the `searchkick` extra the same way now, but I will probably leave also the old way in place, because searchkick takes the page and per_page options natively.
