### ISSUE TITLE
Integrate with Graphql

### ISSUE THREAD

**Issue by lufutu** [ddnexus/pagy#133]
Can Pagy integrate with Graphql ? I don't want use connection in graphql.
Thanks.

**Comment by ddnexus** [comment]
I don't have any direct experience with GraphQL, but you can integrate pagy with any kind of collection, so I would say yes... Take a look at the doc starting [here](https://ddnexus.github.io/pagy/how-to#paginate-any-collection) and follow the link to the [Pagy::Backend](https://ddnexus.github.io/pagy/api/backend.html).

BTW, with APIs you don't need a lot of functionality like for UIs. You need just first prev next last URLs, that you can provide in your response (see also the [Support extra](https://ddnexus.github.io/pagy/extras/support) for a few helpers useful for that purpose) or (probably better) in your [HTTP headers](https://ddnexus.github.io/pagy/how-to#adding-http-headers). Also notice that very soon pagy will not need any additional gem for HTTP headers, so stay tuned if you are interested.

Please, use the [Gitter Chat](https://gitter.im/ruby-pagy/Lobby) instead of an issue for asking for support (and eventually follow up this topic). Thanks.

**Comment by kapso** [comment]
I came here looking for GraphQL integration as well, and found this - https://github.com/RenoFi/graphql-pagination (uses kaminari though)
