### ISSUE TITLE
Overflow feature does not work with Searchkick and ElasticsearchRails

### ISSUE THREAD

**Issue by molfar** [ddnexus/pagy#138]
Overflow options :last_page does not work with Searchkick extra. With unexisting page number it returns empty results. Tested in "Active mode".
I tried search_index.refresh - but it didnt help.

**Comment by ddnexus** [comment]
I think this is due to the `pagy.rb` initializer example, that was missing the `require 'pagy/extras/overflow'`, leading people to think that you don't have to require the extra. The file has been updated just recently (#134).

Please, ensure you have the following in your `pagy.rb` initializer:

```ruby
require 'pagy/extras/overflow'
Pagy::VARS[:overflow] = :last_page
```
Or pass the `overflow: :last_page` option to the `pagy_searchckick` method.

**Comment by ddnexus** [comment]
I just found another misleading comment in the `pagy.rb` initializes example: the `:last_page` is not the default anymore. Now it is `:empty_page` and I will update it.

You probably relied on the indicated default, which is actually not the default. Sorry.

**Comment by molfar** [comment]
You know, I already included overflow extra in initializer, set option to last_page and even reloaded rails server. And it does not work. May be there is some other reason...

**Comment by ddnexus** [comment]
Interesting! Could you share a minimal app that reproduce the problem? As an alternative you should post more code detailsm

**Comment by molfar** [comment]
https://github.com/molfar/pagy_searchkick - here is demo app. There is seed script. And two paginated listings: from db and from searchkick. In searchkick one, you can go to nonexistent page - and got empty results.

**Comment by ddnexus** [comment]
Confirmed bug! I am working on it. Thanks.
