### ISSUE TITLE
single-page should not render a navigation

### ISSUE THREAD

**Issue by grosser** [ddnexus/pagy#16]
seems kinda useless to have a navigation when there is nothing the user can do

**Comment by ddnexus** [comment]
Just wrap the nav in a condition, so you will have what you want, and whoever needs the empty tag for whatever reason can be happy too. I should add a specific how-to.

This specific problem has an historical value for pagy :). You can read a thread [here](https://github.com/kaminari/kaminari/pull/785). That caused me to look into the pagination logic and understand that the solution could be a lot simpler than what usually accepted.

**Comment by espen** [comment]
It would be useful if this was a global setting. Makes it easier with many views.

**Comment by ddnexus** [comment]
Global setting like an explicit helper for _your_ specific need? :)

```ruby
def paginate(@pagy)
  pagy_nav(@pagy) if @pagy.pages > 1          # or whatever other condition
end
```

The logic is: if you call a pagy helper is because you want its output. If you don't... just don't call it. You decide the condition _outside_ pagy.

Adding a global setting and a condition inside every nav helper (and they are quite a lot) just to check something that you should decide _outside_, looks quite silly to me.
