### ISSUE TITLE
Auto sanitize page param ?

### ISSUE THREAD

**Issue by lucasbiguet** [ddnexus/pagy#167]
Hi!

I have a recurring problem in all of my Rails apps, when a malicious user or script tries to perform a SQL injection in the `page` param, `pagy` launches a `Pagy::VariableError` which results in an error 500. Note that `will_paginate` has the same issue except it crashes with a generic error instead.

ie: `http//:my-website.com?page=nasty-SQL-injection` results in an error 500

So:

- Am I alone in this case ? is there something I'm not doing right ?
- Since we cannot prevent people from trying SQL injections in URLs, does it make sense to implement a sanitize param method directly into Pagy to return 1 by default if the `page` param is not a valid integer ? Or is it out of the scope of this gem ?

**Comment by ddnexus** [comment]
Hi @lucasbiquet,

Let me explain a couple of things before entering in the details of that specific case.

It's always tricky to maintain the right balance between what to include and what not include in a gem, especially when the contexts, requirements and preferences could be so different in its usage. 

Pagy as a very slim core and a very fat set of optional/modular extensions by policy. With that policy the core features are super fast, and at the same time everybody could adapt it to the specific context by just requiring the needed extensions in the pagy initializer, or adding a few lines of custom code right in their own code.

The specific `Pagy::Variable` error has been just introduced in order to easily rescue even very specific cases and react according to the personal preferences/requirements (see [Exceptions](https://ddnexus.github.io/pagy/api/pagy#exceptions)).

In the specific case, my opinion is that when somebody is trying to thinker with the app, a 500 error is an appropriate response, however if you want to serve a page regardless, then you can easily do it in your own code rescue-ing from the `Pagy::Variable` error, also considering that you have the accessors to the offending `variable`, its `value` and the original (invalid) `pagy` object.

If you think that it would be a very common case, you can even write a little extension that you could just require. Add a few tests and some doc and you can create a PR to offer the functionality to everybody. ;)

**Comment by ddnexus** [comment]
Something that I forgot to say explicitly... just in case someone might think it's a good idea: sanitizing the params in order to avoid the exception is not convenient, since you would pay the extra cost for all the good requests. Better let only the bad requests to through the extra rescue step.

**Comment by lucasbiguet** [comment]
Indeed, thanks for the explanation it makes perfect sense. I forgot to mention that we use ExceptionNotifier in production, so whenever someone plays with the url and triggers a 500 error I receive an email, which in the case of an automated script results in several hundreds of emails, this is really annoying for us.

But you're right, catching the exception is a better way of handling the issue, I'll think about writing a little extension to handle it gracefully instead.
