### ISSUE TITLE
Missing "go to first" and "go to last" link

### ISSUE THREAD

**Issue by kevinhq** [ddnexus/pagy#173]
Hi. Thanks for the great plugin. Is it intentionally leave the "go to first" and "go to last" link? Or am I missing something here.

I've gone through the doc and all existing closed issues, but it looks like no one mentioned this. I even wen through the source code under template folder, but I don't see them there.

**Comment by ddnexus** [comment]
Hi @kevinhq, yes it is intentional. 

The rationale behind it is that it wouldn't add any functionality that you cannot get without buttons. Indeed you can go to first and last page by clicking on the first and last numbers in the navigation bar (as shown by default).

While the functionality is the same, the advantages of page links are quite a few:

- page links are faster and lighter to render than 2 extra buttons
- page links require no extra coding, no extra configuration, no i18n strings nor maintenance effort compared to buttons, making it all simpler
- page links (i.e. the last one) give feedback about the total number of pages while buttons don't
- page links usually use less real-estate than buttons

Besides that, adding a couple of button would be quite trivial to implement (either using helpers or templates), so it is currently left out of the gem.

HTH
