### ISSUE TITLE
undefined method `per_page' for #<Class:0x00

### ISSUE THREAD

**Issue by dcalixto** [ddnexus/pagy#205]
After change intems to per_page params, someone can spare a hint about this issue?
in the logs show
```

NoMethodError (undefined method `per_page' for #<Class:0x0000565376305000>):
  app/controllers/posts_controller.rb:22:in `index'
```

pagy intializer

```
# frozen_string_literal: true

require 'pagy'
require 'pagy/extras/items'

Pagy::VARS[:items_param] = :per_page # default :items
Pagy::VARS[:max_items]   = 3
Pagy::VARS[:page_param] = :page

```

and controller

```
 def index
    page = params[:page].present? ? params[:page].to_i : 0
    @pagy, @posts = pagy(Post.all)
    hasMore = @posts.length >= Post.per_page
    render json: { posts: @posts, status: 200, hasMore: hasMore }
   end

```

**Comment by ddnexus** [comment]
Hi @dcalixto,
Even if in your code you don't even use it the `page` variable in pagy cannot be 0. Not sure about why you are explicitly setting it that way. FYI: you don't have to handle the :page param, because Pagy do it all for you.

It looks like the error is coming from the `Post.per_page`: unless you defined that, Pagy does not touch the models at all. You can check the `:per_page` request param for that.

It looks like you are implementing some sort of API and the `hasMore` seems to be some metadata. Maybe you may find the `metadata` and `headers` extras useful.

**Comment by dcalixto** [comment]
Hello @ddnexus, 
thank you for your help!
yeah i got that the page cannot be 0! is will_paginage config vice!
So the pagination is detached from the model array! 
I'll try to get more into it! and thank you for the time!

**Comment by ddnexus** [comment]
> So the pagination is detached from the model array!

Here is why pagy [stays away from the models](https://ddnexus.github.io/pagy/index#stay-away-from-the-models)
