### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by helmutrs** [ddnexus/pagy#210]
Since I replaced kaminari for Pagy, The server CPU went up from 7% average to 100% :O. I haven't found out exactly why it happens yet, but after 2 days of server shut down because of CPU went to the roof, I reverted back to Kaminari and the CPU went down to the regular average of 7%.

My specs:
- Ruby 2.6.5
- Rails 5.2.3
- Nginx
- Passenger
- Mysql

I'm gonna try to use Pagy over the weekend on a testing site, see if I can find the bug and I'll post it here. Thanks.

**Comment by ddnexus** [comment]
A few questions:

1. Which is the process that is eating up the CPU? How is that related to Pagy?
2. What exactly did you change in the rails app? Going through the commit diff should give you some clue if it's really related to Pagy.
3. How do you use Pagy? Config? Extensions? Overriding?
4. Can you post the Pagy related code?

**Comment by helmutrs** [comment]
1) Ruby (2 same Ruby process, and most of the time Ruby takes 100% CPU process)
2) The only thing I changed was changed Kaminari to Pagy, so pretty much on the controller from params[:page] to @pagy, @collection = pagy(Model.sql_query), sometimes when the count is not that straight forward, I do pagy(Model.sql_query, count: Model.sql_query.lenght) to give me the count result. On the view from =paginate to = pagy_bootstrap_nav(@pagy)
3) Sometimes I'm using the link_extra: 'data-remote="true"' on the controller so it runs on js instead of full HTML page request.
4) below
5) I removed Kaminari from my Gemfile file, and removed all related code from Kaminari as well.

Controller:
`respond_to do |format|`
			`format.html do`
				`if params[:q]`
					`@search = Account.search_owner(number).search(params[:q])`
					`@pagy, @accounts = pagy(@search.result, count: @search.result.length)`
				`end`
			`end`
		`end`

View: 
`= raw pagy_bootstrap_nav(@pagy)`

**Comment by ddnexus** [comment]
Something that I forgot to ask before: any clue in the logs (rails/nginx/passenger)?

> Ruby (2 same Ruby process, and most of the time Ruby takes 100% CPU process)

Just running the app or under traffic? Did you try just running the app without any request and running it with requests? Any difference in the CPU usage?

> sometimes when the count is not that straight forward, I do pagy(Model.sql_query, count: Model.sql_query.length ) to give me the count result.

What kind of queries are you executing in order to need that?

By looking at the code you posted, I see only the `format.html`. I guess you handle also AJAX calls. 
It looks like you are using something like ransack. Is that the case?

What about running the rails app directly, without nginx/passenger? Do you get the same CPU problem?

Can you provide a minimal app/environment that is affected by the problem?

**Comment by helmutrs** [comment]
- Nothing out of the ordinary on the nginx/passenger nor rails logs, but I'm gonna test it further on our testing server over the weekend to see if I can clarify more.

- I pushed it into production on Friday, so it can give time over the weekend to fix anything if there were any errors that I oversight. So on Friday morning,  the CPU went to the roof, so I add a second server to my load balance so it can give me time to do research, and both servers were pretty much maxed out. At first, I thought it was a misconfiguration or something else on the server, so I changed the server on Friday night and the CPU levels went down (since nobody was working at night and over that weekend) to an average of 15% (due to background long process) which was normal. On Monday morning the CPU went to the roof again, and that's when I decided to revert back to Kaminari gem, and everything went back to normal.

- I don't think the query is a factor, assuming that Pagy and kaminari handle pagination almost identical and I haven't changed my queries when I change of pagination gems (but if you think that would help, let me know, I can provide it) but pretty much is working with 4 models at once (all related to the main object).
- Yes, I handle the ajax queries for some of our paginations, and I'm using ransack. 
- My only test without using nginx/passenger was done a development environment in a Docker container, where we use Puma as server instead of nginx/passenger, so it is pretty hard to see any levels rose up to 100%.
- 

> Can you provide a minimal app/environment that is affected by the problem?

 - Sure, just let me know exactly what you would like, and I'll try to post it here.

hope my answers help.

**Comment by ddnexus** [comment]
I have no idea about how pagy would be able to cause that CPU usage per se. My best guess is that the change from kaminari to pagy introduced some unwanted difference in the app, which has probably nothing to do with pagy itself.

Maybe I could get a better idea if I could see the diff for the change. Would that be possible?

If you are not going to find it directly on your servers, a repo of a minimal environment with a docker or docker-compose setup would be great in order to try to better understand the potential cause. 

Actually reproducing the CPU problem would probably mean adding also nginx and passenger to the environment, so I would let that as the last resort.

**Comment by ddnexus** [comment]
Any news @helmutrs?

**Comment by ddnexus** [comment]
This issue looks abandoned. Assumed invalid.
