### ISSUE TITLE
undefined method `offset' for #<Hash......

### ISSUE THREAD

**Issue by Rubioli** [ddnexus/pagy#216]
Hello to everyone

First of all, I can't wait to test `pagy` and see its efficiency.

I have set up `pagy` in my application, but I have an issue that doesn't make sense to me much and I was hoping someone would shed some light on it.

When I do:

`@pagy, @users = pagy(User.all)`

Everything works fine, but when I have `group_by`, then I get `NoMethodError`:
`@pagy, @users = pagy(User.all.group_by(&:country))`

I have tested my query and everything is fine and only whenever I use `group_by` I get **undefined method `offset' for #<Hash:0x007fbc971e4578>** which I don't understand.

I have also added `require 'pagy/extras/arel'` in my `pagy.rb` initializers, restarted server with no luck. Also used `pagy_arel `.

I appreciate any help and thanks in advance!

**Comment by ddnexus** [comment]
`User.all` is a AR scope, `User.all.group_by(&:country)` is a hash. 

FYI: `group_by` is an extremely bad idea when you have to group AR collection, since it retrieve all the records (potentially millions) and do the grouping on all them (potentially clogging your server, and certainly wasting A LOT of memory in the process), while you need only the few in a page (20 by default).

You should use `group` that will let the DB do the job and pagy will retrieve only the page you need.

**Comment by davidgeilfus** [comment]
> `User.all` is a AR scope, `User.all.group_by(&:country)` is a hash.
> 
> FYI: `group_by` is an extremely bad idea when you have to group AR collection, since it retrieve all the records (potentially millions) and do the grouping on all them (potentially clogging your server, and certainly wasting A LOT of memory in the process), while you need only the few in a page (20 by default).
> 
> You should use `group` that will let the DB do the job and pagy will retrieve only the page you need.

Hi @ddnexus, I'm trying to list user models grouped by the first letter of their name, and use this letter as a heading for each group (like in a typical contact directory, see screenshot below). But I can't wrap my head around how to use `pagy` (or `pagy_arel`) along with `group` to do so. Thank you very much for the help! 🙏

<img width="530" alt="Screenshot" src="https://user-images.githubusercontent.com/1708460/105419342-d79c3b00-5c3e-11eb-920d-28a8598c79ff.png">

**Comment by benkoshy** [comment]
### What I understood:

* You have a contact directory.
* You want to paginate from A to Z.
* On the first page you might have 10 people with their surnames starting with "A". On the second page you might have 4 people with their surnames starting with "B", on the third you might have 5000 people with the surname "C" etc.  
* Or if you don't mind users with the surname "B" and "C" appearing on the same page, simply do something like `ContactDetails.order("surname")` and paginate those results.

If you want pagination links to appear with letters, you might have a hard time doing it:

![image](https://user-images.githubusercontent.com/15097447/105420687-ead9f580-5c94-11eb-869e-241e7f6f3bb4.png)

* The problem is a little tricky: What if there are 210 people with the surname beginning with "A": is it desirable to have 7  pagination links with the letter "A" on it? 

### Suggested approach

I would recommend you give users a search form from A to Z, and then PAGINATE those results (this search for may appear using a series of clickable links). That would work probably a lot more simply than trying to rewrite pagy, if I'm correctly understanding your objective. In other words, use a different scope, and paginate those results. The users will think that they are using "grouping" but strictly speaking you aren't.

**Comment by davidgeilfus** [comment]
Thank you @benkoshy! Since I don't want my pagination to use letters, and I don't mind contacts with surname starting with different letters appearing on the same page, I ended up with this in my controller:

```
@pagy, @paginated_contacts = pagy Contact.order('last_name')
@contacts = @paginated_contacts.group_by{ |contact| contact.last_name[0].upcase }
@contact = Contact.new
```

And this in my view:

```
<% @contacts.each do |letter, contacts| %>
  <h2><%= letter %><h2>
  <ul>
    <% contacts.each do |contact| %>
      <li><%= contact.last_name %></li>
    <% end %>
  </ul>
<% end %>
<%== pagy_nav @pagy %>
```

Thanks again for the help! Cheers
