### ISSUE TITLE
Geared pagination: return 15 elements on page 1, 30 on page 2, 50 on page 3, and 100 from page 4 and forward.

### ISSUE THREAD

**Issue by rosendi** [ddnexus/pagy#225]
What is the best way to implement a pagination like https://github.com/basecamp/geared_pagination?

>Geared Pagination allows you to define different ratios. By default, we will return 15 elements on page 1, 30 on page 2, 50 on page 3, and 100 from page 4 and forward. This has proven to be a very sensible set of ratios for much of the Basecamp UIs. But you can of course tweak the ratios, use fewer, or even none at all, if a certain page calls for a fixed-rate scheme.

**Comment by ddnexus** [comment]
Hi @rosendi 
The trick to add that kind of pagination to pagy would basically require the overriding of the Pagy `initialize` method, particularly changing the logic of the following lines: 

https://github.com/ddnexus/pagy/blob/133da1649871c5aa5238f12b92e4ba2dc81251ea/lib/pagy.rb#L24-L29

The best way would be writing an extra which would be a subclass of `Pagy`, reimplementing the constructor by calculating the instance variables in that lines in a different way. The extra should be also consider the interaction or incompatibility with other extras like the `items` and the `countless` extras for example.

Because of the simplicity of Pagy, it should be quite simple.

**Comment by rosendi** [comment]
@ddnexus Hi,

Would you like to see this feature as an official extra?

**Comment by ddnexus** [comment]
I was not necessarily referring to a published extra, I was just saying that an extra would be the most useful way to implement that even if it is for private use.

IMO a published extra would have quite limited usage. It guess it might make sense for [auto-incremental pagination](https://ddnexus.github.io/pagy/extras/support), but I don't see a practical intuitive usage with a UI. In that case the user is expecting the page links to return pages of the same size, just because that is the usual pagination UI. Besides the `pages` (number of pages) would be tricky to calculate and would be a bit misleading for the user.

What would be your specific use case?

**Comment by ddnexus** [comment]
@rosendi should we consider this closed?

**Comment by rosendi** [comment]
Yep! Closing it! Thank you.

**Comment by ddnexus** [comment]
@rosendi Just stumbled on this after having completely forgotten that this issue even existed!

FYI: it has been implemented with the [gearbox extra](https://ddnexus.github.io/pagy/extras/gearbox)

**Comment by rosendi** [comment]
hehe 🤗 thank you!
