### ISSUE TITLE
More lenient page-parameter handling: is that something you want/would consider?

### ISSUE THREAD

**Issue by nathanvda** [ddnexus/pagy#236]
Hi there, thank you for your awesome gem! I have been a happy user of your gem on a few sites now, but this morning one of my sites got in a some kind of an "attack" where they tried to ... I am not sure what they actually hope to accomplish ... but I could see they were trying all kinds of `page` parameters, e.g. something like 

    /posts?page=utl_inaddr.get_host_address((chr(126)||chr(65)||chr(57)||chr(54)||chr(49)||chr(53)||chr(67)||chr(55)||chr(56)||chr(52)||chr(51)||chr(48)||chr(68)||chr(126))) 

and this caused a lot of problems, because `Pagy` throws a `VariableError`, sending an exception mail ... 

This, in general, is not something I would want. I would want incorrect paging data to silently be ignored or converted to something that works. E.g. in this case I would have preferred to pretend no page parameter was given. 

I have now forked your gem and made a very small adjustment making sure I ignore incorrectly formatted page-parameters. While this works for me, this breaks a lot of tests, and now I am wondering if this is a change you would be considering? I am willing to fix the tests, but it changes "the contract" obviously and maybe not in a way you would prefer. 

So I am not sure if this is the correct approach. On the one hand, it seems a bit weird to throw an exception when the paging parameter is not as expected, because that effectively breaks the website (users visiting experience), but obviously it only breaks the experience for users tampering (malicious or not) with the url. In my specific case, the exception handling caused so much work, my website went offline, but I am also looking at other measures to fix that (rate-limiting/attack blocker/...).

**Comment by ddnexus** [comment]
Interesting.

I discussed raising exceptions and how to handle them in an old issue (#102). I you read that you should first read the last message of the thread in order to make an up-to-date usage of all the messages in the thread.

As you can read in that issue, the official position until now is: if you want to relax params input (in your case to avoid exception emails or for whatever other ideological preference) you can easily do so by the usual ruby means, i.e. rescue the exception you need and bend the pagy logic to your personal/application logic.

With the new Pagy exception structure you can be extremely precise on what you want to rescue, so I believe it should not be a concern of the gem.

In my personal opinion I prefer classes that protect their own logic with very strict exceptions. Exceptions give the class consistency and give you feedback, still giving the option to bypass them when you want.

If we would include relaxed params handling in the gem we would actually reduce the feedback and options for the users.

**Comment by nathanvda** [comment]
Ow thanks for pointing me to the discussion. I tried looking through the old issues but did not directly find anything related (but I see a.o. the exception name has changed in the meantime). 

I completely understand your point of view.

**Comment by ddnexus** [comment]
#167 one is also pertinent

**Comment by ddnexus** [comment]
@nathanvda I am starting to thing that it is a more common case that what I tought.

If you feel in the mood and think it would be useful for you and others, you could write a little extension, and as an extension explicitly required, it would not be an imposed choice on the user, so it could be included.

**Comment by nathanvda** [comment]
Personally now I am more leaning towards: if someone is tampering, I actually indeed want to be notified, however annoying it is (because what makes it annoying is the amount: if my site is attacked I should not be adapting my site to "not be notified", but I should be taking defensive measures instead). So I am more looking into that.

Thank you for your time and input.

**Comment by ddnexus** [comment]
Services like New Relic should handle that case quite well.

**Comment by RyanTG** [comment]
While I agree that VariableError exception emails are annoying and that also it's not great to suppress them, my solution is a fail2ban rule with rack-attack when bad params are entered. Maybe this is extreme, but there's really no legitimate use case for entering garbage params. And furthermore, our pagy routes are being hit by pentesters way more often (or more loudly) than other routes.

So I did this in the rack attack config:

```
  Rack::Attack.blocklist('fail2ban pentesters') do |req|
    Rack::Attack::Fail2Ban.filter(
      "pentesters-#{req.ip}",
      maxretry: 1,
      findtime: 10.minutes,
      bantime: 3.hours
    ) do
      CGI.unescape(req.query_string) =~ %r{page=\D} ||
    end
  end
end
```

Not sure if there are any big flaws in this approach. Basically if a query string includes page=something_other_than_a_digit then BAN. This was based on observing that many of the param attempts start with something like `page='` or some other character that isn't a number.
