### ISSUE TITLE
Option to Limit the Number of Pages Outputted by the Nav Helper

### ISSUE THREAD

**Issue by mc962** [ddnexus/pagy#253]
I have a case where I want to limit the number of pages that Pagy displays using the view helper, regardless of the number of results returned from my query.

For example:
On a page with 25 results per page, and 200 results, instead of 8 pages and 1-25 of 200 results, it should be capped with a max of 4 pages, and a max of 100 results displayed in the views:
```
// top
1-25 of 100+ results
// bottom
1 2 3 4
```
With less results returned in the query than the 'max', it would look like so:
```
// top
1-25 of 60 results
// bottom
1 2 3
```

While some things have already been done to work with the top (a method with a custom implementation was used), the only way I've seen to work with the bottom is to pass a 'fake' (often lower) value into `count`, which forces Pagy to output that lower number of pages. I then pass in an additional value to `vars`, in case I need to access the 'real' count later.

I was curious if there was a better way of limiting the number of pages outputted by the pagy nav helper if needed, especially if it can be done without faking the `count` variable.

**Comment by ddnexus** [comment]
> I was curious if there was a better way of limiting the number of pages outputted by the pagy nav helper if needed, especially if it can be done without faking the count variable.

If I understand your goal correctly... yes.

What you want to do is calculating a variable number of `:items` (which is arbitrary in nature), depending on the `:count` (which is a specific value coming from your data), in such a way that it will determine the "right" number of pages for your logic.

Pagy calculates the number of pages based on count and items, roughly doing ` pages = count / items`. Since you know the optimal number of pages for your logic, then you should roughly do something like `items = count / optimal_pages_based_on(count)`.

Then you can pass the calculated items to the `pagy` contructor in your controller (best when you have different needs in different actions), or override the `pagy_get_items` method with your logic right in your controller (best when the login will be the same for all actions).

HTH

**Comment by mc962** [comment]
Thank you for the quick response.

That helped with getting the correct number of pages. 
However, if I understood what you meant correctly, as well as the documentation on `:items`, then this solution will be saying that `the requested number of items for the page` is some number that might not accurately reflect the total number of items per page, which may cause issues with other attributes such as `:to`.

For example, in a query returning 10,000 items, to get maximum of 4 pages, would be a value of about 3333 for `:items`. This would get the correct number of pages, but when we use `:to` to display the top results info section, it displays like `1-3,333 of 10,000`, which does not reflect what we want to show.

It seems a bit like I want to preserve the current behavior of `:from` and `:to`, while also affecting the number of displayed pages (if that's possible with what is currently available).

**Comment by ddnexus** [comment]
If you pass the `:items` variable number to the `pagy` constructor, everything will work as expected. 

However, my suggestion about overriding the `pagy_get_items` method was incomplete. In that case you should also ensure that the `:items` variable passed to the `Pagy.new` has to be the one you calculate. That needs the overriding of the `pagy` method as well. Sorry for the partial info.
