### ISSUE TITLE
Remove Links object

### ISSUE THREAD

**Issue by CarlosUvaSilva** [ddnexus/pagy#255]
I'm integrating this gem in my project using:

```
pagy, records = pagy(records)

@paginate_params = pagy_headers_hash(pagy)
```

But I don't want the Links object, I just need the item/page info. how do I turn off links?
Thank you

**Comment by ddnexus** [comment]
Not sure I understand what you need. I guess you are using the headers extra. If you do, then the links are the core of the RFC-8288, so there is no real "turn off" for it. 

If you really want to remove it, then I am not sure you really need the headers extra, however since that method returns a hash, you can just delete the `'Link'` key from the result and use your modified hash, or just override the method and remove it in your override.
