### ISSUE TITLE
 Pagination of pages from external api

### ISSUE THREAD

**Issue by SynthesisOne** [ddnexus/pagy#262]
Hi i am getting data from external API such as total number of pages, how can pagination be done if i am not using ActiveRecord?

**Comment by BKSpurgeon** [comment]
What are you trying to do? It's not altogether clear.  Are you able to give an example? Do you control the external API?

**Comment by SynthesisOne** [comment]
> What are you trying to do? It's not altogether clear. Are you able to give an example? Do you control the external API?


I send a request to an external api, specifying the "page" parameter and per_page, in response I receive a part of the pages and also the total number of pages so that I can make pagination

**Comment by BKSpurgeon** [comment]
@SynthesisOne 

As I understand it,  you want to create some pagination links on the front end / client side given those parameters sent to you by the external API?

Here is the answer:

- I'm going to assume that you DO NOT control the external API. If that's the case, then your best and easiest course of action would be to find out what / how pagination is handled by that external API. If they're using pagy, then great: you're in luck: just follow the instructions here: https://ddnexus.github.io/pagy/api/javascript  -- if they aren't using pagy, then unless that API conforms to the interface pagy expects, you might have to hack around a little bit to make it work. Or you could simply roll your own solution.

- If you DO control the API (regardless of active record or otherwise) then the solution is relatively simple, add pagy to your back end api and also add pagy to your front end: https://ddnexus.github.io/pagy/api/javascript or you could render it in html as well https://ddnexus.github.io/pagy/api/frontend if you want to go down that route.

any further questions feel free to ask. 

My understanding of pagy is limited, perhaps @ddnexus can comment if i've made some mistakes above.

**Comment by SynthesisOne** [comment]
Thanks for the complete answer, I have already found the solution
