### ISSUE TITLE
`:max_items` only limits returned records if an `:items_param` is supplied

### ISSUE THREAD

**Issue by caiwilliamson** [ddnexus/pagy#287]
`:max_items` (<https://ddnexus.github.io/pagy/extras/items>) only limits returned records if an `:items_param` is supplied, otherwise the number of returned records is always determined by `Pagy::VARS[:items]` (20 by default). For example...

In `pagy.rb` initializer...
```ruby
require 'pagy/extras/items'
```
In a controller...
```ruby
params[:page] = 1
params[:items] = 100

@pagy, @records = pagy(Message.all, max_items: 5) 
# returns 5 records as expected
```
```ruby
params[:page] = 1
params[:items] = nil

@pagy, @records = pagy(Message.all, max_items: 5) 
# returns 20 records, expected 5
```
```ruby
params[:page] = nil
params[:items] = 100

@pagy, @records = pagy(Message.all, max_items: 5) 
# returns 5 records as expected
```
```ruby
params[:page] = nil
params[:items] = nil

@pagy, @records = pagy(Message.all, max_items: 5) 
# returns 20 records, expected 5
```

**Comment by caiwilliamson** [comment]
I think I have found the culprit of this bug here: https://github.com/ddnexus/pagy/blob/master/lib/pagy/extras/items.rb#L20-L21

```ruby
vars[:items] ||= (items = params[vars[:items_param] || VARS[:items_param]]) &&
                 [items.to_i, vars.key?(:max_items) ? vars[:max_items] : VARS[:max_items]].compact.min
```

When `params[:items]` is not passed i.e. `params[:items] = nil`, the left hand side of the comparison evaluates to `nil`, resulting in a `nil` assignment for `vars[:items]` i.e.
```ruby
vars[:items] ||= (items = params[vars[:items_param] || VARS[:items_param]]) && ...
vars[:items] ||= (items = params[nil || :items]) && ...
vars[:items] ||= (items = params[:items]) && ...
vars[:items] ||= (items = nil) && ...
vars[:items] ||= nil
```
That means that the Pagy instance is initialized with `items: nil`, for example:
```ruby
Pagy.new(count: 1000, items: nil)
```
The constructor will ignore this `nil` var, and instead `Pagy::VARS[:items]` (20 by default) will be used.

**Comment by ddnexus** [comment]
Sorry for the delay, I needed a bit of free time to think to this problem clearly.

First of all, kudos for finding a problem, finding a good solution, setting up the environment to run the tests (did you use docker?), write the tests and create a PR. Amazing work and perseverance!

So to recap... the whole items extra is there in order to get the items from the `params` and eventually cap them to `max_items` if they requested too many. In practice the `params` can override the backend, up to the `max_items`. 

Frankly I never thought that someone could have a use-case that limit the overriding interface to a lower `max_items` than the  `items` allowed by the backend. Shouldn't that work the other way around? 

Usually the `items` extra has a very useful application when your app has a user interface and an API: you would typically paginate the user pages with a lower number of items than what would be allowed with an API client-application. That is usually hungry of records and tries to suck up a lot of records at once, hence the limit. In practice the `max_items` is a quite high limit that you set based on what is the maximum query that you want to pull from your DB, in order to manage your hardware wisely.

What is the use case to set a `max_limit` lower than what you allow with the default items produced by your own backend?

**Comment by ddnexus** [comment]
One more thing to clarify: currently the `items` extra is checking whether there is an overriding by the `params`: if there is one, it limits it to the `max_items`; if there is none, then it goes out of the way and your backend takes over.

The implicit assumption is that you setup the `max_item` in order to cap requests that could abuse your resources, not to cap your own backend, so the `max_items` should limit the `params` that you don't control, not your own backend.

Does that make sense?

**Comment by caiwilliamson** [comment]
Yes that makes sense. I'm building an API so I'm using it as you described. Perhaps I didn't initially grasp the use of `Pagy::VARS[:items]` as a kind of safe default for the number of returned items (which I can simply set to a lower number) when there are no params supplied. So I guess this change is not neccessary! I think I ended up understanding the code better after digging into it, but didn't reflect on my original motivations for changing it until your comments.

However, what would I do in the case that I had multiple pagy instances in my app for different types of records, but I wanted a different default number of items returned for each one? I know I could limit the `max_items` for each one individually, but `Pagy::VARS[:items]` is a global default, and `vars[:items]` will always override the params. For example, I might want something like:

```ruby
@pagy, @records = pagy(Llama.all, default_items: 100, max_items: 1000)

@pagy, @records = pagy(Penguin.all, default_items: 25, max_items: 200)
```

**Comment by ddnexus** [comment]
It should be possible to add arbitrary key/values pairs to the `Pagy::VARS` hash. They get merged with the instance vars when the Pagy object get created, so you should be able to set any default of any custom variable. However that is useful only for your own non-builtin variables.

For variables that pagy uses internally (like the `:items` in the item extra) you will have to handle that manually, and pass the result of your logic to the pagy constructor. For example, the following should work, also persisting the custom item params in the links:

```ruby
@pagy, @records = pagy(Llama.all, items_param: :llama_items,
                                  items: params[:llama_items].to_i.positive? || 100,
                                  max_items: 1000)
@pagy, @records = pagy(Penguin.all, items_param: :penguin_items,
                                    items: params[:penguin_items].to_i.positive? || 25,
                                    max_items: 200)
```
