### ISSUE TITLE
I18n Extra no longer performs as expected in pagy >= 4.0.0

### ISSUE THREAD

**Issue by whithajess** [ddnexus/pagy#290]
We have the following in our `config/initializers/pagy.rb` file:
```
# Use the standard I18n gem - avoids special cases for new translations.
#
# https://ddnexus.github.io/pagy/api/frontend#using-the-standard-i18n-gem
#
require 'pagy/extras/i18n'
```
And have had it in for all previous versions of pagy working correctly up until upgrading past `3.12.0` where we saw errors like so in tests:
```
ActionView::Template::Error:
  undefined method `t' for Pagy::Frontend::I18n:Module
```
commenting out the `require 'pagy/extras/i18n'` line fixes this.

Im assuming its related to this change: https://github.com/ddnexus/pagy/commit/f1d89a5

**Comment by whithajess** [comment]
Can confirm reverting the refactoring fixes the bug.

**Comment by ddnexus** [comment]
Thank you for the report. Can you take a look at why the tests don't fail?

**Comment by whithajess** [comment]
^ @ddnexus its basically a namespace collision issue

**Comment by ddnexus** [comment]
Thanks for the test that exposes the problem.

As you pointed out it's a namespace problem. The `I18n` module name to prepend is an homonym of the `I18n` gem namespace, and either we impose to all the user to write `::I18n` when they mean the gem namespace - which doesn't seem a good idea :) - or we can just rename the module to prepend with a sane `UseI18nGem` name, and we solve the conflict and pass the test.

If you have time, please could you fix it by changing the name, instead of reverting the commit to the ugliness of alias chaining (that we were using only to please old rubies)? If you create a new PR, please, add the new test, which is important.

Thank you

**Comment by whithajess** [comment]
Fix including test pushed ^

**Comment by whithajess** [comment]
@ddnexus would be great to get this merged and released.
