### ISSUE TITLE
Trim & Custom URLs

### ISSUE THREAD

**Issue by sunny** [ddnexus/pagy#325]
# Documentation Issue

- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference/report/post that solves this problem
   
   - [x] The documentation is missing
   - [ ] I am providing the link of the documentation page/document displaying the issue

### Description

Is there a way to use the [trim extra](https://ddnexus.github.io/pagy/extras/trim.html) at the same time as [custom urls](https://ddnexus.github.io/pagy/how-to.html#enabling-fancy-routes) in Pagy 4? This used to work on Pagy 3.13.

Thank you!

**Comment by ddnexus** [comment]
If you didn't change the code that was running on 3.13, then it might be a problem of the order of overriding or who know what else.
I can take a look if you can provide one of the following support to reproduce it:

- a plain ruby file that can run as `ruby my-problem.rb`
- edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
- link of your own branch forked from one branch of the [pagy-rails app](https://github.com/benkoshy/pagy-rails)
- link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
- `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

**Comment by sunny** [comment]
Sure!

Here’s [pagy_standalone_app.ru](https://gist.github.com/sunny/f261dce70f382b4af73c461430de2e6d) with : 

- `def pagy_url_for`
- `Pagy::VARS[:trim] = true`
- a new Sinatra route for `/page/:page`



✅ When on `/` : 

![image](https://user-images.githubusercontent.com/132/129683007-8ce08a93-9d11-45e3-b249-df8a6b2cc501.png)

💥 When on `/page/2` the "Prev" buttons disappear : 

![image](https://user-images.githubusercontent.com/132/129682550-183db486-bcc7-4d14-aa6a-72051988605b.png)

Also, the link on “1” points to `/page/1`.

**Comment by ddnexus** [comment]
@sunny I added to the doc and to the code. Please, use `4.10.2`.

**Comment by sunny** [comment]
Awesome! This regexp worked for my case (I’ve updated the standalone gist):

```rb
def pagy_trim(_pagy, link)
  link.to_s.sub(/\bpage\/1\b/, '')
end
```

Thank you @ddnexus for maintaining pagy at such a high standard! 💪🏻
