### ISSUE TITLE
Reverse the changelog

### ISSUE THREAD

**Issue by tagliala** [ddnexus/pagy#345]
# Documentation Issue

- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
   
   - [ ] The documentation is missing
   - [x] I am providing the link of the documentation page|document displaying the issue

### Description

Hi, 

is it possible to reverse the changelog so we can have newer versions at the top of the file?

Ref: https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md

Thank you!

**Comment by ddnexus** [comment]
> is it possible to reverse the changelog so we can have newer versions at the top of the file?

That's how it was till the last mayor version, and since nobody complained in years... I guess you are right. 🙂

FYI: The reason it is reversed now is probably just because when it was created for 5.0 and for a couple of minor enhancement versions made in just a few days, it made sense to read it from the beginning since the breaking changes where the most important part for users. However, it is a bit annoying when I update it now.

I may add a link to the breaking changes right on the top of the document, and then go down with the old reversed way.

**Comment by tagliala** [comment]
> it made sense to read it from the beginning since the breaking changes where the most important part for users. 

Thanks for the change and the explanation, it makes perfectly sense and I really like the new format with breaking changes linked on top and deprecations

**Comment by ddnexus** [comment]
and thank you for your report! 🙂
