### ISSUE TITLE
Add ca: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#581]

**Comment by benkoshy** [comment]
@AbelToy 

Thank you again for your contribution to the ca locale.

We are in the process to improve the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label: 
      one: "?"
      other: "?"
```

Please, feel free to post a comment with your translations. You don't need to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/ca.yml#L8) (if you don't want to): we can manage it crediting you.

Thank you in advance for your help!
