### ISSUE TITLE
Add cs: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#582]

**Comment by benkoshy** [comment]
@pruzicka

Thank you again for your contribution to the cs locale.

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label:
      one: "?"
      few: "?"
      other: "?"
```

If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/cs.yml#L8) or alternatively post a comment and we can manage it crediting you.

Thank you in advance for your help!

**Comment by pruzicka** [comment]
> @pruzicka
> 
> Thank you again for your contribution to the cs locale.
> 
> We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards.
> 
> We are seeking your advice with the pluralized translation of the "Page", "Pages" label, for each required plural listed below:
> 
> ```yaml
>     page_label:
>       one: "?"
>       few: "?"
>       other: "?"
> ```
> 
> If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/cs.yml#L8) or alternatively post a comment and we can manage it crediting you.
> 
> Thank you in advance for your help!

Ha, sorry I've missed the message and I saw it seconds ago. Thanks @borama
