### ISSUE TITLE
Add nn: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#595]

**Comment by benkoshy** [comment]
@tersor 

Thank you again for your contribution to the nn locale.

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
       page_label: 
      one: "??"
      other: "??"
```

If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/nn.yml#L8) or alternatively post a comment with the translations and we can manage the PR crediting you.

Thank you in advance for your help!

**Comment by tersor** [comment]
@benkoshy

Thank you for the headsup, [PR created](https://github.com/ddnexus/pagy/pull/630).

**Comment by benkoshy** [comment]
Thank you for your contribution. it is merged.
