### ISSUE TITLE
Add pt: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#597]

**Comment by benkoshy** [comment]
@tiagotex 

Thank you again for your contribution to the pt locale.

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label:
      one: "??"
      other: "??"
```

If you are inclined feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/pt.yml#L8) or alternatively post a comment with the translations and we can manage the PR crediting you.

Thank you.

**Comment by tiagotex** [comment]
@benkoshy I will create a PR with the translation :)
