### ISSUE TITLE
all talk and no examples

### ISSUE THREAD

**Issue by grosser** [ddnexus/pagy#6]
tried to add this to my app and had to do a scavenger hunt through the docs, please include basic examples like this one:

```
# Gemfile
gem 'pagy'

# controller
include Pagy::Backend

def index
  @page, @users = page(User.all, page: params[:page], items: 25)

# helper
include Pagy::Frontend

# view
<%= pagy_nav(@pagy).html_safe  %>
```

**Comment by ddnexus** [comment]
Right! Will do! Thanks.

**Comment by ddnexus** [comment]
Hey! I just remembered that I did that long ago :).

What about this [Quick Start](https://ddnexus.github.io/pagy/how-to#quick-start). Does that count as an example or it is just "all talk"?

**Comment by ddnexus** [comment]
@grosser closing this. Please, reopen if needed.

**Comment by grosser** [comment]
The example I posted is as long as the `easy to use` section and shows all the basics, so I'd prefer that.
Atm people that come in and copy-paste things get 2 undefined method errors and then escaped html, also they need to figure out how to set the page-size, which afaik most users will need.

**Comment by ddnexus** [comment]
> Atm people that come in and copy-paste things get 2 undefined method errors and then escaped html
Not sure to understand what you say: html copy and paste works from the browser without picking any html char, what are the 2 undefined method error?

Page size will be moved right after the example, so it will read as part of the same thing Thanks for that.

**Comment by dwieringa** [comment]
First, I'd like to mention I have been impressed with the amount and polish of the documentation.  It speaks a lot to the care for the gem.

I, however, ended up finding this issue trying to figure out why I was having HTML tags show up on my index page instead of the nav bar.

I'm using slim, and my issue went away when I changed `= pagy_nav(@pagy)` to `= pagy_nav(@pagy).html_safe` as grosser recommends in his example.  [Quick Start suggests `<%== pagy_nav(@pagy) %>`]

Even when I switch my view from slim to erb, I still see the same issue.

I'm newer to Ruby and Rails.  Did I do something wrong?  I'm guessing more detail should be added to the Quick Start? (or some bug fixed?).

**Comment by dwieringa** [comment]
Ah, wait, I see how that I'm short a `=`.

**Comment by ddnexus** [comment]
@dwieringa yes, that is the template equivalent of `html_safe`

**Comment by grosser** [comment]
neat, never new that <%== is a thing ... might still be good to recommend
`.html_safe` since it's more obvious / makes people more aware of not
putting user content in there

**Comment by stevenchanin** [comment]
For people using HAML, the shortcut for `html_safe` is `!=`:
```
!= pagy_nav(@pagy)
```

**Comment by aaronbrethorst** [comment]
I had figured that the `==` was a typo in the docs. It'd be helpful to know that was intentional and functionally identical to `.html_safe`. Great gem, thanks for your hard work.

**Comment by ddnexus** [comment]
@aaronbrethorst Yes, that's something long due (also suggested by others) that I always forgot to add. Will do.

BTW, while the `<%== ` or equivalent is embedded in the template system and is agnostic to the type of app you use, the `html_safe` is a specific `ActiveSupport` method, hence is not agnostic and not so consistent with pagy.

**Comment by aaronbrethorst** [comment]
@ddnexus got it. thanks again!
