### ISSUE TITLE
Add uk: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#606]

**Comment by benkoshy** [comment]
@yshmarov we are hoping you speak "East Slavic" `uk` locale? If not apologies for them spam, but if so: we need your help:

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label:
      one: ""
      few: ""
      many: ""
      other: ""
```

If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/uk.yml#L8) or alternatively post a comment with the translations and we can manage the PR crediting you.

Thank you in advance for your help!

**Comment by yshmarov** [comment]
Hi @benkoshy . My pleasure!

**Comment by ddnexus** [comment]
Merged by mistake because it's missing a fix.
