### ISSUE TITLE
Add vi: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#607]

**Comment by benkoshy** [comment]
Uses the "other" pluralisation rule. Perhaps "pages" will suffice.

**Comment by benkoshy** [comment]
Thank you again for your contribution to the vi locale.

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label: "Trang ??"
```

If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/vi.yml#L8) or alternatively post a comment with the translations and we can manage the PR crediting you.

Thank you in advance for your help!

**Comment by ddnexus** [comment]
> Perhaps "pages" will suffice.

If we are sure of the `vi` translation...

**Comment by YutoYasunaga** [comment]
@benkoshy 
Hi, for the `page_label`, I suggest using `"Trang"` for both singular and plural contexts. This is aligning with the natural expression in Vietnamese.

**Comment by ddnexus** [comment]
Implemented in  c33c33b9
Thank you @YutoYasunaga
