### ISSUE TITLE
Add zh-HK: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#609]

**Comment by benkoshy** [comment]
@thattimc 

Thank you again for your contribution to the zh-HK locale. 

We are in the process of improving the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "pages" label, for each required plural listed below:

```yml
	page_label: "Pages (plural) in the locale ?"
```

If you are inclined: feel free to create a [PR](https://github.com/ddnexus/pagy/blob/aria/lib/locales/zh-HK.yml#L8) or alternatively post a comment with the translations and we can manage the PR crediting you.

Thank you in advance for your help!
