### ISSUE TITLE
How to get total_count with 'items:X'

### ISSUE THREAD

**Issue by technodrome** [ddnexus/pagy#65]
Hello,

First of all, a massive thank you for extremely dedicated help I see here on your issue tracker. I am very impressed and want to express my thanks for your amazing work :)

Mine is more of a question, not a bug per se.

I have 3 different scopes for Blog state based on whether a blogpost has a publication date assigned with it or not. Then on the page I show the user the count of all three categories of a blogpost: published, scheduled and drafts. 

BlogsController:
```ruby
  def index
    published ||= Blog.published(params[:user_id])
    drafts    ||= Blog.draft(params[:user_id])
    scheduled ||= Blog.scheduled(params[:user_id])

    @pagy, @published = pagy(published, items: 10)
    @pagy, @drafts    = pagy(drafts, items: 10)
    @pagy, @scheduled = pagy(scheduled, items: 10)
  end
```
View:
```ruby
%span.badge.badge-secondary #{@published.count}
#... and so on
```
However, if I define `items: 10` (any number really) in the Blogs controller, then if I use `@published.count` in my view, I always get that `items` number as total number of published posts, which is incorrect. What I want is real **total count** of all published items, not number of `items` per page. In Kaminari, one has `total_count` which circumvents this side effect. 

So three questions, if I may:
a) How to get total count in a Ruby way in Pagy?
b) Do I need to redefine `@pagy` IVAR in my controller for all three blogpost types?
c) Is it OK to use IVAR caching `||=` here?

Thank you for taking a moment to review this.

**Comment by ddnexus** [comment]
Hi @technodrome and thanks for the thanks :)

If you have read the doc and you still have the doubt about overriding the Pagy args/vars, then I will have to improve the doc, because it is always possible to override any var by just passing it to the `pagy` controller method. In your case it would be `count: your_count`.

However what you are doing in the action is completely obscure to me and looks wrong, so I need more context. Could you add some more details about what helpers you use in the view and how? 

About your page: do you render 1 page of Blog records (not filtered by their state) and 1 pagination nav (with the breakdown of 3 partial published/drafts/scheduled counts)  or 3 page of records with 3 pagination navs (published/drafts/scheduled)?

**Comment by technodrome** [comment]
Hello, so to clear up:

I am calling index action on BlogsController to render all blogs with `published` scope. So 1 pagination on `index` page for `published` only. 

That scope is defined in the Blog model as:

```ruby
  scope :published, lambda { |author|
    joins(:user)
      .select('blogs.*, users.first_name, users.last_name, users.username')
      .where('users.username = ?', author)
      .where.not(published_at: nil) # has a publication date set
      .where('published_at <= ?', Time.zone.now) # and this date is in the past or now
  }
```
I do believe this is not that important from Pagy's point of view.

So on that Blog's index page I am simply paginating list of these `published` blogs. On the same page I also use a small partial to show a little statistics with total number of blogposts - published, drafts and scheduled, like wordpress does. No magic here either, therefore I need all three instance variables populated in the `index` action.

I do not want to override number of published paginated items on the index page. I want to get their total count. In DB I have 13 published posts, but `items: 10` in `@pagy, @published = pagy(published, items: 10)` causes my total count to show always 10 instead of 13.

As for the other two `pagy` calls on the index action, I did this to be able to let user show published, draft or scheduled posts on the index page via AJAX request - so to replace 1 paginated list of `published` blogposts with respective `draft` or `scheduled` paginated list via AJAX on the index page. This is, however, not active yet, so AJAX does not interfere. There is no JS code written yet.

```ruby
# future-proofing, we want to give users the ability to replace paginated published posts with any other type of post
drafts    ||= Blog.draft(params[:user_id])
scheduled ||= Blog.scheduled(params[:user_id])

@pagy, @drafts    = pagy(drafts, items: 10)
@pagy, @scheduled = pagy(scheduled, items: 10)
```

Helpers:
I am using Pagy code in Application helper only to enable responsive Bootstrap pagination:

```ruby
  # show Pagy only if we have more than one page in pagination
  def paginate(collection)
    pagy_nav_bootstrap_responsive(collection).html_safe if collection.pages > 1
  end
```

Does this clear things up?

**Comment by ddnexus** [comment]
OK, so now that is more clear, it looks more wrong! :)

If I understand correctly, you have an action to show and paginate the published posts by default, but let the user choose to see the draft or scheduled posts, which would be replaced in the page by an AJAX call. Right?

If that is correct, then here are a few very wrong things in the action:

1. With `local ||= scope` you are not caching anything, since the `local` will be always `nil` at the moment of the execution of the line. Besides, even if that would work, you don't need to cache any scope, since a scope doesn't execute any query (which would be the expensive action that you might want to cache). That's a wrong caching concept and implementation.

2. You are paginating 3 scopes each time you call that action, while you actually would need to paginate only 1: the one that you are supposed to show to the user, and generate the `nav` for.  You are re-assigning `@pagy` 3 times, and the first 2 times are totally useless, since they will get overridden by the 3rd assignation. Not only that: the object contained in `@pagy` contains ALWAYS the pagination variables calculated for the scheduled posts (3rd assignation), regardless your intentions to paginate the published posts.

3. Your claim that you get the wrong count of published posts because you pass the `items: 10` is very wrong, because - first of all - the count passed in by the `pagy` call (which is stored in the `@pagy` variable) is the count of the scheduled posts as explained above. If you do `@pagy.count` you will get the actual `scheduled.count`. You are probably trying to get the count from the paginated records (which is not what you should do). The `@scheduled.count` will be the count of the page of record you happen to serve with the current page, i.e. 10 records for all the pages but the `@pagy.last` page, which could could have count < 10 (unless the total count of record is a multiple of 10).

Here is a possible working recipe to get what you want:

```ruby
def index
  # sanitize the :scope param
  scope_name      = params[:scope] if %w[published draft scheduled].include(params[:scope])
  scope_name    ||= 'published'
  @pagy, @records = pagy(Blog.send(scope_name.to_sym, params[:user_id]), items: 10)
end
```

You will have to pass the `:scope` param (eventually improving it in the route definition). That way you can get the paginated scope as `@records` and the right `@pagy` variable. No need to override anything.

For your little statistics you may want to organize your `Blog` model to use the `group` and `count`, so to have a Hash count of the blogs, or whatever may fit your purpose, however, keep in mind that you need just 3 integers to display. You should probably create a helper to use the `blog_state_count` in your views.

HTH

**Comment by technodrome** [comment]
Thank you very much for an extraordinarily detailed description. You helped a lot.
I forgot local variables are just that - local. Three calls to `pagy` were not really well though through. 

While your solution is wonderfully simple (I love code like that and get inspired by people who write it instantaneously) and I understand Pagy a bit more now, it still does not solve the problem because of which I created this ticket. You will not get total number of published posts, only paginated, on the first page. It is revealed in the generated SQL - it will not show the total count, as it inserts `LIMIT 10` in the Rails log (see the last line):

```sql
SELECT COUNT(count_column) 
FROM (SELECT  blogs.*, users.first_name, users.last_name, users.username AS count_column FROM "blogs" INNER JOIN "users" ON "users"."id" = "blogs"."user_id" 
WHERE (users.username = 'technodrome') 
AND ("blogs"."published_at" IS NOT NULL) AND (published_at <= '2018-07-08 20:34:52.350094') 
ORDER BY published_at DESC LIMIT $1 OFFSET $2) subquery_for_count  
[["LIMIT", 10], ["OFFSET", 0]]
```

Kaminari's `total_count` does not put this `LIMIT` in the SQL to be able to get total number of published records. So if I understand you correctly, there is no Pagy native way to get total number of all published (not paginated on the current page) posts?

**Comment by ddnexus** [comment]
`@pagy.count` is the total count of whatever has been paginated (i.e. published). By design Pagy doesn't add anything to the collection (see [why](https://ddnexus.github.io/pagy/index#stay-away-from-the-models)).

**Comment by technodrome** [comment]
Fantastic. I will have to refactor my code a bit, but now I know how to get total number of posts regardless of their type. You are right, `@pagy.count` it is.

Thank you again for first class help! You've got yourself one more happy Pagy user :)

**Comment by ddnexus** [comment]
>You've got yourself one more happy Pagy user :)

Happy to help.... Then if you give a star to Pagy it would be very appreciated! Thanks.

**Comment by technodrome** [comment]
Sure thing, done!

**Comment by ddnexus** [comment]
Thanks

**Comment by iamunadike** [comment]
after {pagy_merge_headers(@pagy) if @pagy} not working as the response headers does not contain the the extra headers by pagy
already allowed in config/initializers/pagy.rb (default cause I simply required extras/headers

**Comment by iamunadike** [comment]
in the FE. response.headers does not contain the page , total-count  etc
as expected ,

**Comment by ddnexus** [comment]
@iamunadike you posted your issue in an apparently unrelated issue, which is also closed, so it will likely not get any attention.

Reading at your post: you should check that your code is correct and that you are checking the right things. From the outside it looks like a problem with your implementation more than a pagy issue.

If you determine that it is actually an issue with pagy, please, [create a new issue](https://github.com/ddnexus/pagy/issues/new?assignees=&labels=&template=Code.md&title=)

**Comment by iamunadike** [comment]
I can tell you this category 
Rails Backend::

------------------- Some Controller -------------------
include Pagy::Backend
after {pagy_merge_headers(@pagy) if @pagy} 
def index
@pagy, @services  = pagy(Service.all)
render json: @services
end

---- > this issue here is the merge headers is not working as expected in the pagy response
in Vue.js 3 Frontend
import axios
async getServices(){
let response = await axios.get(service_index_url, {credentials})
#... when I have a promise and a response ....
response.headers['Total-Count'] is undefined
#along others like page , items etc
#it should be in the headers response 
}

**Comment by ddnexus** [comment]
As I already told you:

1. An unrelated and closed ticket IS NOT the place where to post your issue!
2. You have to check your code and you did not. It doesn't even run!

I will delete any further unrelated post in this thread. Please, use the proper channels to post your issues.
Thanks
