### ISSUE TITLE
Docs: Which branch should PRs be made against?

### ISSUE THREAD

**Issue by Earlopain** [ddnexus/pagy#650]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

In the readme "How to contribute" doesn't mention this.

I'm sure it would be either dev or main. Mostly dev perhaps?
> The master branch is the latest rubygem-published release. It also contains docs and comment changes that don't affect the published code. It is never force-pushed.

So docs only changes go to main directly? Code changes to dev? I'm not entirely sure how to parse this.

It would be nice if the contributing section mentions this. In #648 you changed the base branch. If most of the changes will go to dev, would it make sense to change the default branch to dev as well? This would also give a better insight into activity instead of only seeing commits by default if a release is done.

**Comment by ddnexus** [comment]
> So docs only changes go to main directly? Code changes to dev? I'm not entirely sure how to parse this.

Yes, you got it. Admittedly it's not completely like that though, and it is not written in stone: the little note that you quoted is just there to declare what is force-pusheed and what is not.

However, here is a bit of clarification (or maybe confusion :smile:): on how we usually use the branches.

Files (not necessarily code, e.g. locales) that will go into the gem must get tested/reviewed before going to master, hence dev. Scripting, utilities and other code not going into the gem might go directly to master, but if they are strictly related to the gem code (e.g. test) they usually pass into dev first. In practice we test them in some other branch first, because I don't want to commit some crap to master (that I cannot force push).

>  If most of the changes will go to dev, would it make sense to change the default branch to dev as well? 

Good observation. However the "most changes" could go either ways, depending on the period. 

If we are refactoring internal automation or docs (and they are supposed to be many) they are passing through an intermediate branch (that could even be dev when a release is very stable and we don't expect bugs or PRs) and when ready, we merge to master.

If we are refactoring gem code, then we are certainly working on dev and there will be a lot of commits (that we might squash, so you will not see all that stuff into master).

So that is the first problem with using dev as a fixed default branch: there is no certainty about "most changes".

The biggest problem though is that github considers the default branch very special and we encountered a few things that are github default-branch based and not configurable, so we just gave up the whole idea. 

Admittedly if we were more disciplined we could have a "release" branch that we can use to merge things that go into the gem, and use master as the current dev and promote it to default, but dev is too volatile, and it would not be a good reference point for anybody. 

So in conclusion what's on master it's what is in the gem, plus the other stuff of the repo.

About the specific reason I merged your PR into dev instead of master... it's just because I was working on the CHANGELOG in dev and I knew that I would have a release today, and I wanted to add a small sentence to your commit, so it was just more convenient for me.

In conclusion, basing a PR on master is the best option for everybody, because it's trivial for us to change the base branch, and contributors don't have to worry about all that reasoning that is possibly influenced by the particular period and other external factors. So thank you for your concern, but feel free to use master as base branch: the important thing is having your contributions, the base branch is almost irrelevant.

Thank you!

**Comment by Earlopain** [comment]
Thanks for the comprehensive anwser. My main point of confusion here is that contributing doesn't mention branches at all, yet there is some info on those below which to me looks like it would be relevant for that.

If you're saying, "yup, we have some rules but you shouldn't need to worry about all that, just use main" would it make sense to add that to the contribution section?

**Comment by ddnexus** [comment]
> yet there is some info on those below which to me looks like it would be relevant for that.

The intention of "branches" was just giving a general info about what you could expect to find into the repo, for the braves that browse it.
Sort of a high level repo-map.

> If you're saying, "yup, we have some rules but you shouldn't need to worry about all that, just use main" would it make sense to add that to the contribution section?

People base the PR on master by default, by if indeed someone is diligent enough to have the doubt, maybe a simple short sentence would help... We can simply write something like "please base your PR on the master branch",
