### ISSUE TITLE
Feature request: Helpers for HTTP headers and HTML <link> tags

### ISSUE THREAD

**Issue by NARKOZ** [ddnexus/pagy#78]
HTTP headers:

Link: `<www.example.com/article-part2; rel="next">` for the next article segment.
Link: `<www.example.com/article-part2; rel="prev">` for the previous article segment.

HTML <link> tags:

`<link rel="next" href="next_page_URL">` for the next article segment.
`<link rel="prev" href="previous_page_url">` for the previous article segment.

https://support.google.com/webmasters/answer/1663744?hl=en

**Comment by ddnexus** [comment]
The `rel` attributes are already added to the pagination links of the HTML tags, so that should solve the problem already.

The HTTP headers may be useful for API, but they are not a concern of Pagy at the moment, since there are a couple of gems that support Pagy that do that for you in a quite automatic way.

Please, take a look at:
- [api-pagination](https://github.com/davidcelis/api-pagination)
- [pager-api](https://github.com/IcaliaLabs/pager-api)

**Comment by NARKOZ** [comment]
Thanks!
