### ISSUE TITLE
pagy(..., page: #) seems to be ignored

### ISSUE THREAD

**Issue by polyethylene1and2** [ddnexus/pagy#97]
I'm setting the page number manually with `pagy(Collection.all, page: page)` in my view (my site framework doesn't use a `params` variable), but this generates a NameError: "undefined local variable or method `params`".
I get the same error when I don't specify the `page` option, so I'm guessing `page` is being ignored?

**Comment by ddnexus** [comment]
The `:page` variable does not get ignored: the execution doesn't even arrive to create the `Pagy` instance, because the `Pagy::Backend` is assuming there is a `params` method in your controller.  

Please, take a look at the [Environment Assumptions](https://ddnexus.github.io/pagy/how-to#environment-assumptions) for clue about why that happens and how to easily avoid it.

**Comment by polyethylene1and2** [comment]
From that page:
> However you can force a page number by just passing it to the pagy method. For example:
> ```@pagy, @records = pagy(my_scope, page: 3)```
> That will explicitly set the `:page` variable, overriding the default behavior (which usually pulls the page number from the `params[:page]`).
Doesn't this mean that I don't need a `params` variable/method at all, if I am always explicitly setting the page number?

**Comment by ddnexus** [comment]
Forcing/overriding the page number happens AFTER the params method is
called.

**Comment by ddnexus** [comment]
In other words: you have first to satisfy the environment assumptions (which requires a `params` method or an overridden `pagy_get_vars` that avoids to call it), and then if you want explicitly override the `:page` variable you can pass it to the `pagy` method. However that is for single instance overriding or variable addition.

Since you have to override the `pagy_get_vars` to avoid the `params` call, I would suggest you to set the `:page` in that method, which _raison d'être_ is exactly collecting the variables (including the `:page`) for the `Pagy` creation. 

BTW, what framework are you using and where do you get the `:page` from?

**Comment by ddnexus** [comment]
You may also want to read the [ Pagy::Backend doc](https://ddnexus.github.io/pagy/api/backend) that could give you more insights about the `pagy` method.

**Comment by ddnexus** [comment]
Glad that you made it work. 

However, overriding `pagy_get_vars` is not the only way.  You can [write your own `pagy` method](https://ddnexus.github.io/pagy/api/backend#writing-your-own-pagy-methods) and bypass the `pagy_get_*` methods altogether.

For sequel you need also to override he `:count` assignment from `collection.count(:all)` to `collection.count` (but you should already know that by now).
