### ISSUE TITLE
Option for not showing next/prev when no page

### ISSUE THREAD

**Issue by espen** [ddnexus/pagy#99]
It would be useful if it was possible to hide the next/prev link when there is no page to go to. For example no next link on the last page or no prev link on the first page.

**Comment by ddnexus** [comment]
It is possible.
The links have an extra `disabled` class "when there is no page to go to", so you can pick and hide them with a `display: none;` CSS rule.

**Comment by ddnexus** [comment]
@espen What about this issue? It looks invalid to me, so it should be closed.

**Comment by espen** [comment]
Well I disagree with you but feel free to close it 😅

I think the helper should be responsible for this. Not only more convenient when implementing but I think it's the right place to handle it. The helper is responsible for the visual output. If there is no need to show it then I think it should be up to the helper to decide it, at least for generic things like this. But it's not a big thing to implement in the view so it's not a huge hassle the way it is now. Another thing to note; I migrated from kaminari so first I followed the readme and replacing the view helper. Worked great. Then going through testing I noticed this problem and I assumed it would work as kaminari or at least give a global option to control it. As it didn't I had to replace the 10 or so helper calls with extra code. Again, not a big thing, but it would be smoother and easier to migrate with this option. But again: up to you and I respect your decision. I understand you want to keep the gem small and focused, which is a good way of looking at things.

**Comment by ddnexus** [comment]
Thank you for your feedback! I understand your point, and it makes sense, however it clashes with 2 things: performance and code simplicity, which have the highest priority in Pagy.

The consequence of that priorities is a big part of the reason you enjoy a super-fast and light pagination (and I guess one of the reasons you migrated from Kaminari :))

Replacing the helper calls with extra code instead of adding one singe imple CSS rule costs you some IPS, some simplicity and probably some little memory: you decide if it is worth in your own code. Including it in the Pagy code would impose the cost (albeit small [*]) on every user, even if they don't need the option or even if they would prefer CSS to remove it. 

[*] the performance of Pagy are made possible thanks to many very little choices like that one
